name: Camden
favicon: null
layout_spectrum: 0.5209
typography_spectrum: 0.12217
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0063a4'
    - '#fffde8'
    - '#cbb3c1'
    - '#000200'
    - '#465d09'
  brandStrength: 0.9375
  lightness: 0.8125
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
